### ISSUE TITLE
Installs too recent zfs binaries

### ISSUE THREAD

**Issue by gfriloux** [eoli3n/archiso-zfs#13]
Hello, taking latest archiso from https://mirrors.gandi.net/archlinux/iso/2022.11.01/archlinux-2022.11.01-x86_64.iso we get broken ZFS installation due to mismatch libcrypto versions.

This leads to the following error:
```
> Installing zfs-utils and zfs-linux
error: command failed to execute correctly
```

Invoking any `zfs` command will output the following error:
```
zfs: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory
```

**Comment by gfriloux** [comment]
Updating `openssl` package will fix `zfs` binaries, but will break any base binary or archiso relying on `librcrypto`.
I don't know what you can do on your side to fix this, but this makes your script broken.

**Comment by eoli3n** [comment]
From the readme

> In some very specific cases, you won't be able to get ZFS module working for a specific archiso version.
> In that case, just switch to the previous month iso.

The new one is out in two days, let's see if it fixes it.

**Comment by gfriloux** [comment]
Ok, i'd like to move forward in less than 2 days, i'll try to update only packages that depends on openssl (avoiding kernel update), and if i fail, i will work on my patience xD (2 days is nothing in reality).

Thanks for the quick answer btw!
I'm still running my personnal computer with an arch installed with your work!

**Comment by eoli3n** [comment]
The big part of the work is @minextu from https://github.com/archzfs/archzfs
But thank you.

**Comment by Reuenthal767** [comment]
I had the same problem, but I was able to work around it by:
1. increasing the cowspace **before** running @eoli3n  the script
2. running `sudo pacman -Syu` as the current arch iso is too old and new to update to fix that problem
3. running @eoli3n script and to the rest as usual

**Comment by gfriloux** [comment]
It seems doing `pacman -S openssl-1.1 openssl` is enough.

**Comment by gfriloux** [comment]
Confirmed.
If you run under this issue, run:
```
pacman -S openssl-1.1 openssl
```

**Comment by AkechiShiro** [comment]
Hey @eoli3n shouldn't openssl be installed/upgraded by the script ? Since zfs depends on `libcrypto.so.3` which is from the `openssl` package on Archlinux, I'm not sure why is that not done, it can lead to issues I guess with the rest of the packages since it's like a partial upgrade?

I ran into the issue above as well but I'm using an old Archiso file `archlinux-2022.11.01-x86_64.iso`

**Comment by eoli3n** [comment]
Is that issue still occurring on latest archiso ?

**Comment by AkechiShiro** [comment]
@eoli3n It wasn't happening on the latest I had downloaded at the time (using the latest fixed the issue), sorry I thought I left a comment and I never did, guess was under too much load.
