### ISSUE TITLE
Script fails because a package of currently running kernel is not available

### ISSUE THREAD

**Issue by WildPenquin** [eoli3n/archiso-zfs#15]
Hi,

I'm using the official Arch liveimage, downloaded yesterday. It is possible the Kernel just got upgraded in the repositories.

Either way the script fails here:
```
> Installing zfs-utils and zfs-linux
warning: zfs-utils-2.2.0-1 is up to date -- reinstalling
warning: cannot resolve "linux=6.5.9.arch2-1", a dependency of "zfs-linux"
error: failed to prepare transaction (could not satisfy dependencies)
```

My Kernel version on the live image is the above, but it is not available in the repositories anymore:

```
 # uname -a
Linux archiso 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux
```

**EDIT:** Debug.log is here: http://sprunge.us/HqWHpF

**Comment by eoli3n** [comment]
I can't reproduce, but I just improved the way errors trigger dkms fallback in dev branch.
Would you like to:
- retry with command in the readme ? I think it was just fixed upstream in archzfs repository.
```
$ curl -s https://raw.githubusercontent.com/eoli3n/archiso-zfs/master/init | bash -s -- -v
```
- if you still get the same error, retry with that command, which just switch to the dev branch.
```
$ curl -s https://raw.githubusercontent.com/eoli3n/archiso-zfs/dev/init | bash -s -- -v
```

**Comment by WildPenquin** [comment]
Yes, this is the version I'm running:
```
944fe27e085b9fa1abbb0b3de7110db8  archlinux-2023.11.01-x86_64.iso
```

However, for whatever reason, after rebooting zfs installed now correctly. It's either the changes you've made, or the fact I had already grown airootfs size manually on the last boot. I'm not sure how that could have caused the failure. I didn't do anything else on the previous boot.

But if it seems I'm the only one with the issue and even then a one-of occurrence, I believe this one can be closed =).

Thank you !

**Comment by WildPenquin** [comment]
Actually, I believe I know what may have happened.

I did grow the airootfs for a reason: I installed some packages (tmux) onto the live installation. However, doing so I obviously pulled in the main package cache. I may re-test this later, but my hypothesis is the script may fail if the main package db has been synchronized.

**Comment by eoli3n** [comment]
Yes, I recommend you to run archiso-zfs at first, just after the boot, it takes care of the whole init, then you can install any package you like.
