### ISSUE TITLE
ArchZFS repo inconsistent results

### ISSUE THREAD

**Issue by Thermi** [eoli3n/archiso-zfs#2]
For the Archlinux ISO from july 1st (archlinux-2020.07.01-x86_64.iso), the script sometimes finds a matching zfs-utils and zfs-linux version, sometimes not. Seems that the archzfs repo is either hosted redundantly, but inconsistently, or the script has some problems.

**Comment by eoli3n** [comment]
FYI:
- added: https://github.com/eoli3n/archiso-zfs#debug
- about 2020.08.01: https://github.com/archzfs/archzfs/issues/354

It seems to be the same problem with 2020.07.01, can you confirm ?
I did 4 tries, and i can't reproduce your problem.

**Comment by eoli3n** [comment]
archzfs/archzfs#354 fixed for 2020.07.01 and 2020.08.01 isos.
Please let me know if you still have problems.
